apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jkwilliams3-dev/myfullstack.git
    targetRevision: main
    path: charts/myapp
    helm:
      values: |
        image:
          repositoryBackend: "mybackend"
          tagBackend: "local"
          repositoryFrontend: "myfrontend"
          tagFrontend: "local"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
