apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jkwilliams3-dev/myfullstack.git'
    targetRevision: HEAD
    path: 'charts/myapp'
    helm:
      values: |
        image:
          repositoryBackend: "<ACR>.azurecr.io/mybackend"
          tagBackend: "develop-1234"
          repositoryFrontend: "<ACR>.azurecr.io/myfrontend"
          tagFrontend: "develop-1234"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
